### ISSUE TITLE
Telluric mask crashes with out of bounds

### ISSUE THREAD

**Issue by bprinoth** [Hoeijmakers/tayph#110] opened 2022-06-14 13:51 UTC
After producing the telluric mask in masking mode, it cannot be applied and crashes with the following error: 

> masking.mask_orders(list_of_wls,list_of_orders_mask,dp,maskname,mw,c_thresh,
>   File "/home/bibi/GitHub/tayph/tayph/masking.py", line 1228, in mask_orders
>     list_of_masks_telluric[i][:,int(j)] = np.nan #These are like list_of_orders but with
> IndexError: index 9110 is out of bounds for axis 1 with size 9110

It seems like it has not realised that the orders have different sizes. When running tayph with make_mask False, it runs through... 

While masking the tellurics, the following errors are printed in the terminal: 

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/matplotlib/cbook/__init__.py", line 270, in process
>     func(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/matplotlib/widgets.py", line 530, in <lambda>
>     return self._observers.connect('changed', lambda val: func(val))
>   File "/home/bibi/GitHub/tayph/tayph/masking.py", line 763, in slide_T_margin
>     self.select_telluric_regions()
>   File "/home/bibi/GitHub/tayph/tayph/masking.py", line 440, in select_telluric_regions
>     sel = self.x_axis[self.telluric1d < self.tcut]
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 9110 but corresponding boolean dimension is 7115

Could that be the problem?

**Comment by Hoeijmakers** [comment] 2022-08-10 15:56
I believe that this has been solved, and I cannot reproduce the error when looking at orders with tellurics close to the edge ( > 7115 pixels). I will close this until it comes back up.

**Closed by Hoeijmakers** 2022-08-10 15:56 UTC
